export const zIndex = {
  BACKGROUND_ELEMENTS: -1,
  BASE_CONTENT: 1,
  PROJECT_CARD_HOVER: 10,
  PROJECTS_SCROLL_BUTTONS: 20,
  NAVIGATION_MOBILE_MENU: 40,
  NAVIGATION: 50,
  CUSTOM_CURSOR: 50,
  PROJECT_DETAIL: 60,
};
