import { Project } from './types';

export const NAVIGATION_LINKS = [
  { name: 'Portfolio', href: '#home' },
  { name: 'Profile', href: '#profile' },
  { name: 'Projects', href: '#projects' },
  { name: 'Contact', href: '#contact' },
];

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    title: 'CHAGEE和萌友们',
    category: 'style & workflow optimization',
    group: 'spatial',
    thumbnailUrl: '/images/projects/p1-thumbnail.png',
    images: [
      { src: '/images/projects/p1-0.png', name: '萌友-66' }, 
      { src: '/images/projects/p1-1.png', name: '萌友-kuku' }, 
      { src: '/images/projects/p1-2.png', name: '萌友-33 一娃 小5 腊八' }, 
      { src: '/images/projects/p1-3.png', name: '萌友-nini' }, 
      { src: '/images/projects/p1-4.png', name: '萌友-lucky' }, 
      { src: '/images/projects/p1-5.png', name: '萌友-肉桂' }, 
      { src: '/images/projects/p1-6.png', name: '萌友-urus' }, 
      { src: '/images/projects/p1-7.png', name: '萌友-coconut' }
    ],
    description: '在小程序上线宠物季DIY专属宠物杯的活动，需要AIGC实现宠物风格化，提供了目标风格图片。主要负责整个流程搭建，风格调试，批量验证。',
    year: '2025',
    role: 'AI Designer',
    client: 'CHAGEE'
  },
  {
    id: 'p2',
    title: 'Find & Spot',
    category: 'UI Design & AIGC',
    group: 'product',
    thumbnailUrl: '/images/projects/p2-thumbnail.png',
    images: ['/images/projects/p2-0.jpg', '/images/projects/p2-1.jpg'],
    description: 'A collection of ceramic tableware celebrating the imperfections of hand-molding. Each piece is unique, reflecting the wabi-sabi philosophy.',
    year: '2025',
    role: 'Product Designer',
    client: 'Kiki Ceramics'
  },
  {
    id: 'p3',
    title: 'Paper & Shadow',
    category: 'Brand Identity',
    group: 'identity',
    thumbnailUrl: '/images/projects/p3-thumbnail.jpg',
    images: ['/images/projects/p3-0.jpg', '/images/projects/p3-1.jpg'],
    description: 'Rebranding for a heritage tea shop in Kyoto. We utilized textured paper stocks and embossing to create a tactile brand experience.',
    year: '2022',
    role: 'Art Director',
    client: 'Uji Tea Co.'
  },
  {
    id: 'p4',
    title: '筑梦岛-乙女风格模型',
    category: 'lora train',
    group: 'spatial',
    thumbnailUrl: '/images/projects/p4-thumbnail.png',
    images: ['/images/projects/p4-0.jpg', '/images/projects/p4-1.jpg'],
    description: '筑梦岛APP希望在AI虚拟角色设定的玩法内上线乙女（女性向）人像风格，现有动漫1.3.1模型文生图的乙女风格效果较单一，无法满足客户对乙女风格的需求，因此选择定制训练乙女风格Lora模型，以增强动漫1.3.1模型的乙女风格化效果。',
    year: '2024',
    role: 'AI Designer',
    client: '筑梦岛'
  },
   {
    id: 'p5',
    title: 'SAMSUNG 儿童Portrait',
    category: 'comfyui workflow',
    group: 'spatial',
    thumbnailUrl: '/images/projects/p5-thumbnail.png',
    images: ['/images/projects/p5-0.jpg', '/images/projects/p5-1.jpg'],
    description: 'A gallery space designed to disappear, allowing the art to take center stage. Minimalist structures with maximum impact.',
    year: '2025',
    role: 'Architect',
    client: 'Modern Art Foundation'
  },
  {
    id: 'p6',
    title: '残碑',
    category: 'Game Design & Art Design',
    group: 'product',
    thumbnailUrl: '/images/projects/p6-thumbnail.png',
    images: ['/images/projects/p6-0.jpg', '/images/projects/p6-1.jpg'],
    description: 'Cast iron cookware designed for longevity and generational transfer. The textured surface improves with age and use.',
    year: '2024',
    role: 'Industrial Designer',
    client: 'Foundry X'
  },
  {
    id: 'p7',
    title: 'Woven Light',
    category: 'Product Design',
    group: 'product',
    thumbnailUrl: '/images/projects/p7-thumbnail.jpg',
    images: ['/images/projects/p7-0.jpg', '/images/projects/p7-1.jpg'],
    description: 'Bamboo light fixtures that cast intricate shadows. Merging traditional weaving techniques with modern LED technology.',
    year: '2023',
    role: 'Designer',
    client: 'Lumina'
  },
  {
    id: 'p8',
    title: '阿尔山乡村艺术季',
    category: 'Arch Renovation and Exhibition Curation',
    group: 'identity',
    thumbnailUrl: '/images/projects/p8-thumbnail.png',
    images: ['/images/projects/p8-0.png', '/images/projects/p8-1.png'],
    description: 'Visual identity for a calligraphy school. The logo is dynamic, generated by ink simulation software to be different every time.',
    year: '2023',
    role: 'Architect',
    client: 'CAFA & Hinggan League'
  },
  {
    id: 'p9',
    title: 'Mono',
    category: 'Brand Identity',
    group: 'identity',
    thumbnailUrl: '/images/projects/p9-thumbnail.jpg',
    images: ['/images/projects/p9-0.jpg', '/images/projects/p9-1.jpg'],
    description: 'A brutalist identity for an experimental music label. Strict adherence to black and white with heavy typographic focus.',
    year: '2023',
    role: 'Graphic Designer',
    client: 'Mono Records'
  }
];

export const SOCIAL_LINKS = [
  { name: 'Instagram', url: '#' },
  { name: 'Behance', url: '#' },
  { name: 'LinkedIn', url: '#' },
];