import { Project } from './types';

export const NAVIGATION_LINKS = [
  { name: 'Portfolio', href: '#home' },
  { name: 'Profile', href: '#profile' },
  { name: 'Projects', href: '#projects' },
  { name: 'Contact', href: '#contact' },
];

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    title: 'Silence in Stone',
    category: 'Interior Design',
    thumbnailUrl: 'https://picsum.photos/800/600?random=1',
    images: ['https://picsum.photos/800/600?random=1', 'https://picsum.photos/800/600?random=11', 'https://picsum.photos/800/600?random=12'],
    description: 'A residential project focusing on raw materials and natural light. The concept revolves around the idea of silence as a tangible element of space.',
    year: '2023',
    role: 'Lead Architect',
    client: 'Private Residence'
  },
  {
    id: 'p2',
    title: 'Earthen Ware',
    category: 'Product Design',
    thumbnailUrl: 'https://picsum.photos/800/600?random=2',
    images: ['https://picsum.photos/800/600?random=2', 'https://picsum.photos/800/600?random=21'],
    description: 'A collection of ceramic tableware celebrating the imperfections of hand-molding. Each piece is unique, reflecting the wabi-sabi philosophy.',
    year: '2024',
    role: 'Product Designer',
    client: 'Kiki Ceramics'
  },
  {
    id: 'p3',
    title: 'Paper & Shadow',
    category: 'Brand Identity',
    thumbnailUrl: 'https://picsum.photos/800/600?random=3',
    images: ['https://picsum.photos/800/600?random=3', 'https://picsum.photos/800/600?random=31'],
    description: 'Rebranding for a heritage tea shop in Kyoto. We utilized textured paper stocks and embossing to create a tactile brand experience.',
    year: '2022',
    role: 'Art Director',
    client: 'Uji Tea Co.'
  },
  {
    id: 'p4',
    title: 'Moss Garden',
    category: 'Landscape',
    thumbnailUrl: 'https://picsum.photos/800/600?random=4',
    images: ['https://picsum.photos/800/600?random=4', 'https://picsum.photos/800/600?random=41'],
    description: 'An urban sanctuary designed to age gracefully. The selection of flora emphasizes seasonal decay and renewal.',
    year: '2023',
    role: 'Landscape Architect',
    client: 'City Arts Council'
  },
   {
    id: 'p5',
    title: 'Void Space',
    category: 'Architecture',
    thumbnailUrl: 'https://picsum.photos/800/600?random=5',
    images: ['https://picsum.photos/800/600?random=5', 'https://picsum.photos/800/600?random=51'],
    description: 'A gallery space designed to disappear, allowing the art to take center stage. Minimalist structures with maximum impact.',
    year: '2021',
    role: 'Architect',
    client: 'Modern Art Foundation'
  },
  {
    id: 'p6',
    title: 'Raw Iron',
    category: 'Product Design',
    thumbnailUrl: 'https://picsum.photos/800/600?random=6',
    images: ['https://picsum.photos/800/600?random=6', 'https://picsum.photos/800/600?random=61'],
    description: 'Cast iron cookware designed for longevity and generational transfer. The textured surface improves with age and use.',
    year: '2024',
    role: 'Industrial Designer',
    client: 'Foundry X'
  },
  {
    id: 'p7',
    title: 'Woven Light',
    category: 'Product Design',
    thumbnailUrl: 'https://picsum.photos/800/600?random=7',
    images: ['https://picsum.photos/800/600?random=7', 'https://picsum.photos/800/600?random=71'],
    description: 'Bamboo light fixtures that cast intricate shadows. Merging traditional weaving techniques with modern LED technology.',
    year: '2023',
    role: 'Designer',
    client: 'Lumina'
  },
  {
    id: 'p8',
    title: 'Sumi',
    category: 'Brand Identity',
    thumbnailUrl: 'https://picsum.photos/800/600?random=8',
    images: ['https://picsum.photos/800/600?random=8', 'https://picsum.photos/800/600?random=81'],
    description: 'Visual identity for a calligraphy school. The logo is dynamic, generated by ink simulation software to be different every time.',
    year: '2022',
    role: 'Art Director',
    client: 'Sumi Ink School'
  },
  {
    id: 'p9',
    title: 'Mono',
    category: 'Brand Identity',
    thumbnailUrl: 'https://picsum.photos/800/600?random=9',
    images: ['https://picsum.photos/800/600?random=9', 'https://picsum.photos/800/600?random=91'],
    description: 'A brutalist identity for an experimental music label. Strict adherence to black and white with heavy typographic focus.',
    year: '2023',
    role: 'Graphic Designer',
    client: 'Mono Records'
  }
];

export const SOCIAL_LINKS = [
  { name: 'Instagram', url: '#' },
  { name: 'Behance', url: '#' },
  { name: 'LinkedIn', url: '#' },
];